USE [master]
GO

/****** Object:  Database [Interrail]    Script Date: 11/06/2016 12:33:30 ******/
CREATE DATABASE [Interrail]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Interrail', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.TIAGOSERVER\MSSQL\DATA\Interrail.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Interrail_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.TIAGOSERVER\MSSQL\DATA\Interrail_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Interrail] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Interrail].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Interrail] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Interrail] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Interrail] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Interrail] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Interrail] SET ARITHABORT OFF 
GO

ALTER DATABASE [Interrail] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Interrail] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Interrail] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Interrail] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Interrail] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Interrail] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Interrail] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Interrail] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Interrail] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Interrail] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Interrail] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Interrail] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Interrail] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Interrail] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Interrail] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Interrail] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Interrail] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Interrail] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Interrail] SET  MULTI_USER 
GO

ALTER DATABASE [Interrail] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Interrail] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Interrail] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Interrail] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Interrail] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Interrail] SET  READ_WRITE 
GO


